import SAY_AS from './sayAs.json';
import { setSpeaking } from './speaking';

let voice: SpeechSynthesisVoice | null = null;
let rate = 0.8;
// Every utterance is kept until it ends, so the browser never drops one (and its end event) early, even with a line queued behind it.
const live = new Set<SpeechSynthesisUtterance>();

const available = () => typeof speechSynthesis !== 'undefined' && !!speechSynthesis;

export { onSpeaking } from './speaking';

export function setSpeechRate(r: number): void {
  rate = r;
}

/**
 * How clear a voice is: an iPad's downloaded Premium or Enhanced voices are much clearer than the compact default (parent,
 * 2026-10-05). iPadOS often names them all "Tingting"; the quality is in the voiceURI (com.apple.voice.enhanced.zh-CN.…).
 */
export const voiceQuality = (v: SpeechSynthesisVoice): number => {
  const id = `${v.name} ${v.voiceURI ?? ''}`;
  return /premium/i.test(id) ? 2 : /enhanced|增强|高品质|优化/i.test(id) ? 1 : 0;
};

/** The parent's pick (Settings → Voice), by voiceURI; null: the clearest the iPad has. */
let preferred: string | null = null;
export function setPreferredVoice(uri: string | null): void {
  preferred = uri;
  if (available()) voice = pickVoice(speechSynthesis.getVoices());
}
/** The voice speaking now, for the parent's Voice setting. */
export const currentVoice = (): SpeechSynthesisVoice | null => voice;
/** The Mandarin voices this iPad lets the app use, clearest first. */
export function chineseVoices(): SpeechSynthesisVoice[] {
  if (!available()) return [];
  return speechSynthesis.getVoices().filter((v) => /^zh/i.test(v.lang) && !/HK|TW/i.test(v.lang)).sort((a, b) => voiceQuality(b) - voiceQuality(a));
}

export function pickVoice(voices: SpeechSynthesisVoice[]): SpeechSynthesisVoice | null {
  const chosen = preferred ? voices.find((v) => v.voiceURI === preferred) : undefined;
  if (chosen) return chosen;
  const mainland = voices.filter((v) => /^zh[-_]CN/i.test(v.lang)).sort((a, b) => voiceQuality(b) - voiceQuality(a) || Number(b.localService) - Number(a.localService));
  return (
    mainland[0] ??
    voices.find((v) => /^zh/i.test(v.lang) && !/HK|TW/i.test(v.lang)) ??
    null
  );
}

/** Voices load asynchronously on iPad Safari; wait briefly for them. */
export async function loadChineseVoice(timeoutMs = 1500, pref: string | null = null): Promise<SpeechSynthesisVoice | null> {
  preferred = pref;
  if (!available()) return (voice = null);
  // the iPad can add voices after the first list (a downloaded Enhanced one): pick again whenever the list changes
  speechSynthesis.addEventListener?.('voiceschanged', () => { voice = pickVoice(speechSynthesis.getVoices()) ?? voice; });
  voice = pickVoice(speechSynthesis.getVoices());
  if (!voice) {
    voice = await new Promise<SpeechSynthesisVoice | null>((resolve) => {
      const done = () => resolve(pickVoice(speechSynthesis.getVoices()));
      speechSynthesis.addEventListener?.('voiceschanged', done, { once: true });
      setTimeout(done, timeoutMs);
    });
  }
  return voice;
}

/** One or two characters on their own go by in a blink: they are said a quarter slower (parent, 2026-10-05: placement's listening questions). */
export const SHORT_WORD_PACE = 0.75;
const isShortWord = (text: string) => {
  const han = Array.from(text).filter((ch) => /\p{Script=Han}/u.test(ch)).length;
  return han > 0 && han <= 2;
};

/**
 * What the voice is given for a lone character: a common 多音字 is said as a character read only the way the card teaches
 * (调 tiáo → 条), so the voice can't pick its other reading (parent, 2026-10-05). Generated by scripts/gen-say-as.ts.
 */
export function spokenAs(text: string, reading?: string): string {
  const { sayAs, poly, plain } = SAY_AS as { sayAs: Record<string, string>; poly: Record<string, string>; plain: Record<string, string> };
  // a character said on its own between pauses (写一写's "长，长城的，长") is said as taught too
  if (text.includes('，')) return text.split('，').map((part) => (Array.from(part).length === 1 ? spokenAs(part, reading) : part)).join('，');
  if (!(text in poly)) return text;
  if (reading && reading !== poly[text]) return plain[reading] ?? text;
  return sayAs[text] ?? text;
}

/**
 * Say Chinese text. It cuts off whatever is playing, unless `queue` (then it waits its turn: the character, then its usage line).
 * `reading` is the pinyin a lone character is taught with, when the screen knows it.
 */
export function speak(text: string, { queue = false, reading }: { queue?: boolean; reading?: string } = {}): void {
  if (!available()) return;
  text = spokenAs(text, reading);
  if (waiting) {
    // A tap is waiting for Safari to finish cancelling: a queued line joins it, a new tap replaces it.
    waiting.texts = queue ? [...waiting.texts, text] : [text];
    return;
  }
  if (!queue) {
    const busy = speechSynthesis.speaking || speechSynthesis.pending;
    speechSynthesis.cancel();
    setSpeaking(false); // a cancelled utterance may never say it ended
    if (busy) {
      // Safari drops or clips a voice started straight after cancelling one that was playing (parent, 2026-10-05: a sound
      // button tapped again was sometimes silent, sometimes cut short), so it is said a moment later.
      const w: Waiting = { texts: [text], timer: setTimeout(() => {
        waiting = null;
        for (const t of w.texts) say(t);
      }, AFTER_CANCEL_MS) };
      waiting = w;
      return;
    }
  }
  say(text);
}

/** How long Safari is given to finish cancelling before the next voice starts. */
const AFTER_CANCEL_MS = 120;
type Waiting = { texts: string[]; timer: ReturnType<typeof setTimeout> };
let waiting: Waiting | null = null;

function say(text: string): void {
  const u = new SpeechSynthesisUtterance(text);
  const done = () => {
    live.delete(u);
    setSpeaking(false);
  };
  u.onstart = () => setSpeaking(true);
  u.onend = done;
  u.onerror = done;
  live.add(u);
  u.lang = 'zh-CN';
  u.rate = isShortWord(text) ? Math.round(rate * SHORT_WORD_PACE * 100) / 100 : rate;
  if (voice) u.voice = voice;
  speechSynthesis.speak(u);
}

/** Silence any speech in progress (before recording him, and when leaving a screen). */
export function stopSpeaking(): void {
  if (waiting) clearTimeout(waiting.timer);
  waiting = null;
  if (available()) speechSynthesis.cancel();
  live.clear();
  setSpeaking(false);
}

/** iOS only allows speech after a user gesture; call this from the first tap. */
export function primeSpeech(): void {
  if (!available()) return;
  const u = new SpeechSynthesisUtterance(' ');
  u.volume = 0;
  speechSynthesis.speak(u);
}
