// 组词 for characters the HSK word list gave none (parent, 2026-10-05: 一's card had only a 成语; 九, 猫, 鱼… had nothing).
// Written for the app, HSK 1–6 characters only: everyday words a P2 child meets, at the card's reading, with their English.
// [组词, pinyin as said (一/不 with their tone changes, 轻声 toneless), English]

export type ExtraExample = [text: string, pinyin: string, english: string];

export const EXTRA_EXAMPLES: Record<string, ExtraExample[]> = {
  // HSK 1
  几: [['几个', 'jǐ gè', 'how many; a few'], ['几天', 'jǐ tiān', 'a few days; how many days']],
  九: [['九月', 'jiǔ yuè', 'September'], ['九个', 'jiǔ gè', 'nine (of them)']],
  七: [['七天', 'qī tiān', 'seven days'], ['七月', 'qī yuè', 'July']],
  吗: [['好吗', 'hǎo ma', 'OK?; is that all right?'], ['是吗', 'shì ma', 'really?; is that so?']],
  肉: [['牛肉', 'niú ròu', 'beef'], ['吃肉', 'chī ròu', 'to eat meat']],
  呢: [['你呢', 'nǐ ne', 'and you?'], ['他呢', 'tā ne', 'what about him?']],
  差: [['差不多', 'chà bu duō', 'almost; about the same'], ['很差', 'hěn chà', 'very poor; not good']],
  饿: [['饿了', 'è le', 'hungry now'], ['很饿', 'hěn è', 'very hungry']],
  假: [['假的', 'jiǎ de', 'fake; not real'], ['真假', 'zhēn jiǎ', 'real or fake']],
  累: [['累了', 'lèi le', 'tired now'], ['很累', 'hěn lèi', 'very tired']],
  您: [['您好', 'nín hǎo', 'hello (polite)'], ['谢谢您', 'xiè xie nín', 'thank you (polite)']],
  渴: [['口渴', 'kǒu kě', 'thirsty'], ['渴了', 'kě le', 'thirsty now']],
  // HSK 2
  又: [['又来了', 'yòu lái le', 'here it comes again'], ['又一次', 'yòu yí cì', 'once again']],
  亿: [['一亿', 'yí yì', 'one hundred million'], ['亿万', 'yì wàn', 'hundreds of millions']],
  长: [['很长', 'hěn cháng', 'very long'], ['长城', 'cháng chéng', 'the Great Wall']],
  为: [['为什么', 'wèi shén me', 'why'], ['因为', 'yīn wèi', 'because']],
  鸟: [['小鸟', 'xiǎo niǎo', 'little bird'], ['鸟儿', 'niǎo ér', 'bird']],
  只: [['一只', 'yì zhī', 'one (animal)'], ['两只', 'liǎng zhī', 'two (animals)']],
  狗: [['小狗', 'xiǎo gǒu', 'puppy; little dog'], ['狗狗', 'gǒu gou', 'doggy']],
  鱼: [['小鱼', 'xiǎo yú', 'little fish'], ['金鱼', 'jīn yú', 'goldfish']],
  啊: [['好啊', 'hǎo a', 'OK!; sure!'], ['是啊', 'shì a', 'yes!; that\'s right']],
  猫: [['小猫', 'xiǎo māo', 'kitten; little cat'], ['猫咪', 'māo mī', 'kitty']],
  喊: [['大喊', 'dà hǎn', 'to shout loudly'], ['喊叫', 'hǎn jiào', 'to yell']],
  湖: [['湖水', 'hú shuǐ', 'lake water'], ['西湖', 'xī hú', 'West Lake']],
  漂: [['漂流', 'piāo liú', 'to drift; rafting'], ['漂浮', 'piāo fú', 'to float']],
  篇: [['一篇', 'yì piān', 'one (story, piece of writing)'], ['这篇', 'zhè piān', 'this (story, essay)']],
  // HSK 3
  刀: [['小刀', 'xiǎo dāo', 'small knife'], ['刀子', 'dāo zi', 'knife']],
  羊: [['小羊', 'xiǎo yáng', 'lamb; little sheep'], ['羊肉', 'yáng ròu', 'mutton']],
  某: [['某人', 'mǒu rén', 'someone'], ['某天', 'mǒu tiān', 'one day; some day']],
  猪: [['小猪', 'xiǎo zhū', 'piglet'], ['猪肉', 'zhū ròu', 'pork']],
  // HSK 4
  江: [['长江', 'cháng jiāng', 'the Yangtze River'], ['江水', 'jiāng shuǐ', 'river water']],
  县: [['县城', 'xiàn chéng', 'county town'], ['县长', 'xiàn zhǎng', 'county head']],
  呀: [['快呀', 'kuài ya', 'hurry up!'], ['好呀', 'hǎo ya', 'OK!; great!']],
  浅: [['很浅', 'hěn qiǎn', 'very shallow'], ['浅色', 'qiǎn sè', 'light colour']],
  俩: [['我们俩', 'wǒ men liǎ', 'the two of us'], ['他俩', 'tā liǎ', 'the two of them']],
  咸: [['很咸', 'hěn xián', 'very salty'], ['咸菜', 'xián cài', 'pickled vegetables']],
  倍: [['两倍', 'liǎng bèi', 'twice as much; double'], ['一倍', 'yí bèi', 'one time more']],
  逛: [['逛街', 'guàng jiē', 'to go shopping; to stroll the streets'], ['逛公园', 'guàng gōng yuán', 'to stroll in the park']],
  盐: [['食盐', 'shí yán', 'table salt'], ['放盐', 'fàng yán', 'to add salt']],
  棵: [['一棵树', 'yì kē shù', 'a tree'], ['两棵', 'liǎng kē', 'two (trees, plants)']],
  腰: [['弯腰', 'wān yāo', 'to bend over'], ['腰带', 'yāo dài', 'belt']],
  躺: [['躺下', 'tǎng xià', 'to lie down'], ['躺着', 'tǎng zhe', 'lying down']],
  薄: [['很薄', 'hěn báo', 'very thin'], ['薄饼', 'báo bǐng', 'thin pancake']],
  戴: [['戴帽子', 'dài mào zi', 'to wear a hat'], ['戴上', 'dài shàng', 'to put on (glasses, a hat)']],
  // HSK 5
  乙: [['甲乙', 'jiǎ yǐ', 'A and B (first and second)'], ['乙等', 'yǐ děng', 'second grade; grade B']],
  扔: [['扔掉', 'rēng diào', 'to throw away'], ['扔球', 'rēng qiú', 'to throw a ball']],
  闯: [['闯进', 'chuǎng jìn', 'to burst in'], ['闯红灯', 'chuǎng hóng dēng', 'to run a red light']],
  夹: [['夹子', 'jiā zi', 'clip; tongs'], ['夹住', 'jiā zhù', 'to hold tight (with a clip)']],
  吐: [['吐口水', 'tǔ kǒu shuǐ', 'to spit'], ['吐出', 'tǔ chū', 'to spit out']],
  呆: [['发呆', 'fā dāi', 'to stare blankly; to daydream'], ['呆在', 'dāi zài', 'to stay at']],
  吨: [['一吨', 'yì dūn', 'one ton'], ['两吨', 'liǎng dūn', 'two tons']],
  兔: [['兔子', 'tù zi', 'rabbit'], ['小白兔', 'xiǎo bái tù', 'little white rabbit']],
  冠: [['皇冠', 'huáng guān', 'crown'], ['鸡冠', 'jī guān', 'cockscomb (a rooster\'s crest)']],
  咳: [['咳嗽', 'ké sou', 'to cough'], ['咳了', 'ké le', 'coughed']],
  骂: [['骂人', 'mà rén', 'to scold someone'], ['挨骂', 'ái mà', 'to get scolded']],
  洒: [['洒水', 'sǎ shuǐ', 'to sprinkle water'], ['洒了', 'sǎ le', 'spilled']],
  咬: [['咬人', 'yǎo rén', 'to bite (people)'], ['咬一口', 'yǎo yì kǒu', 'to take a bite']],
  臭: [['很臭', 'hěn chòu', 'very smelly'], ['臭味', 'chòu wèi', 'bad smell']],
  弹: [['弹琴', 'tán qín', 'to play the piano'], ['弹钢琴', 'tán gāng qín', 'to play the piano']],
  堆: [['一堆', 'yì duī', 'a pile'], ['雪堆', 'xuě duī', 'snowdrift; pile of snow']],
  梨: [['梨子', 'lí zi', 'pear'], ['吃梨', 'chī lí', 'to eat a pear']],
  猴: [['猴子', 'hóu zi', 'monkey'], ['小猴', 'xiǎo hóu', 'little monkey']],
  紫: [['紫色', 'zǐ sè', 'purple'], ['紫花', 'zǐ huā', 'purple flower']],
  歇: [['歇一歇', 'xiē yi xiē', 'to rest a little'], ['歇脚', 'xiē jiǎo', 'to rest one\'s feet']],
  颗: [['一颗', 'yì kē', 'one (small round thing)'], ['颗粒', 'kē lì', 'grain; pellet']],
  瘦: [['很瘦', 'hěn shòu', 'very thin'], ['瘦了', 'shòu le', 'got thinner']],
  摘: [['摘花', 'zhāi huā', 'to pick flowers'], ['摘下', 'zhāi xià', 'to take off; to pick']],
  // HSK 6
  勺: [['勺子', 'sháo zi', 'spoon'], ['一勺', 'yì sháo', 'a spoonful']],
  井: [['水井', 'shuǐ jǐng', 'water well'], ['井水', 'jǐng shuǐ', 'well water']],
  吞: [['吞下', 'tūn xià', 'to swallow'], ['吞了', 'tūn le', 'swallowed']],
  肺: [['肺部', 'fèi bù', 'lungs'], ['心肺', 'xīn fèi', 'heart and lungs']],
  驻: [['驻地', 'zhù dì', 'base; station'], ['驻守', 'zhù shǒu', 'to guard (a place)']],
  扁: [['压扁', 'yā biǎn', 'to squash flat'], ['扁扁的', 'biǎn biǎn de', 'flat']],
  哇: [['哇哇', 'wā wā', 'waah (a baby crying)'], ['哇哇叫', 'wā wā jiào', 'to wail']],
  捡: [['捡起', 'jiǎn qǐ', 'to pick up'], ['捡到', 'jiǎn dào', 'to find (on the ground)']],
  煮: [['煮饭', 'zhǔ fàn', 'to cook rice'], ['煮面', 'zhǔ miàn', 'to cook noodles']],
  跪: [['跪下', 'guì xià', 'to kneel down'], ['下跪', 'xià guì', 'to kneel']],
  塞: [['塞住', 'sāi zhù', 'to plug; to block up'], ['塞进', 'sāi jìn', 'to stuff into']],
  滴: [['一滴', 'yì dī', 'a drop'], ['水滴', 'shuǐ dī', 'water drop']],
  嘛: [['好嘛', 'hǎo ma', 'OK then'], ['是嘛', 'shì ma', 'is that so?']],
  膜: [['薄膜', 'bó mó', 'thin film'], ['保鲜膜', 'bǎo xiān mó', 'cling film']],
  踩: [['踩到', 'cǎi dào', 'to step on'], ['踩水', 'cǎi shuǐ', 'to splash in water']],
  醋: [['吃醋', 'chī cù', 'to be jealous'], ['白醋', 'bái cù', 'white vinegar']],
  趟: [['一趟', 'yí tàng', 'one trip'], ['走一趟', 'zǒu yí tàng', 'to make a trip']],
  踢: [['踢球', 'tī qiú', 'to kick a ball; to play football'], ['踢足球', 'tī zú qiú', 'to play football']],
  蹲: [['蹲下', 'dūn xià', 'to squat down'], ['蹲着', 'dūn zhe', 'squatting']],
};

/** English for the 组词 above, for the cards and the sheet (the HSK glossary only covers its own words). */
export const EXTRA_GLOSS: Record<string, string> = Object.fromEntries(
  Object.values(EXTRA_EXAMPLES).flat().map(([text, , english]) => [text, english]),
);
