// Content sweep (parent, 2026-10-05): every HSK 1–4 card reviewed for what a P2 child sees — the card's meaning, its 组词's
// pinyin and English — plus a scan of every gloss for slang or adult senses. The dictionary often leads with an archaic sense
// (后 "empress", 店 "inn") or adds slang (鸭子 "male prostitute"); these put the everyday one first.

/** A character's English on its card. */
export const SWEEP_MEANINGS: Record<string, string> = {
  // HSK 5–9 (second sweep)
  "丑": "ugly",
  "旦": "dawn; day",
  "甲": "first; shell; nail",
  "央": "center",
  "仔": "young animal; young man",
  "朵": "measure word for flowers",
  "羽": "feather",
  "竹": "bamboo",
  "纲": "outline; key principle",
  "劳": "labor; work",
  "闲": "idle; free time",
  "版": "edition; version",
  "届": "measure word for sessions/classes",
  "帘": "curtain",
  "奈": "how; to cope with (无奈)",
  "胡": "beard; reckless",
  "挣": "to earn",
  "悄": "quiet",
  "损": "to damage; to lose",
  "谊": "friendship",
  "硕": "large; big",
  "博": "broad; rich (博物馆)",
  "傅": "teacher; master (师傅)",
  "惠": "kindness; benefit",
  "敬": "to respect",
  "款": "sum of money; style",
  "葡": "grape (葡萄)",
  "筑": "to build",
  "尊": "to respect; honor",
  "熊": "bear",
  "豫": "hesitant (犹豫)",
  "赠": "to give as a gift",
  "糟": "bad; messy",
  "予": "to give",
  "允": "to allow",
  "圣": "holy; sage",
  "麦": "wheat",
  "拨": "to dial; to push aside",
  "氛": "atmosphere",
  "拐": "to turn",
  "券": "ticket; voucher",
  "胞": "sibling; cell (细胞)",
  "扁": "flat",
  "档": "file; grade",
  "液": "liquid; fluid",
  "储": "to store; to save",
  "凯": "triumphant; victory",
  "茂": "lush; luxuriant",
  "犬": "dog",
  "龟": "tortoise; turtle",
  "冯": "surname Feng",
  "坝": "dam; dike",
  "捐": "to donate; to contribute",
  "素": "plain; element; vegetarian",
  "蒙": "to cover; ignorant",
  "兰": "orchid",
  "芝": "sesame (in 芝麻); fungus",
  "拟": "to draft; to imitate",
  "凸": "convex; sticking out",
  "驳": "to refute; to reject",
  "驯": "to tame",
  "纽": "button; knob; link",
  "玫": "rose (in 玫瑰)",
  "杭": "Hangzhou",
  "吕": "surname Lü",
  "亩": "mu (unit of land area)",
  "吁": "to sigh; to pant",
  "倾": "to lean; to incline",
  "晓": "to know; dawn",
  "绪": "mood; thread",
  "川": "river; Sichuan",
  "甘": "sweet; willing",
  "镇": "town; to calm",
  "勾": "to tick; to hook; to draw",
  "啦": "sentence particle (了+啊)",
  "欧": "Europe",
  "俄": "Russia",
  "赵": "surname Zhao",
  "唐": "Tang dynasty; surname Tang",
  "秦": "Qin dynasty; surname Qin",
  "饵": "bait",
  "钥": "key",
  "雀": "sparrow; small bird",
  "拧": "to twist; to screw",
  "顷": "hectare (公顷); moment",
  "郑": "surname Zheng; solemn",
  "荡": "to swing; to sway",
  "阀": "valve",
  "岳": "high mountain; wife's parent",
  "帕": "handkerchief",
  "荆": "thorny shrub; brambles",
  "契": "agreement; contract",
  "饶": "to forgive; to spare",
  "馁": "discouraged",
  "凄": "sad; dreary",
  "胳": "arm (胳膊)",
  "峙": "to stand tall; to face off",
  "兼": "both; at the same time",
  "耸": "to tower; to shrug",
  "烹": "to cook",
  "戚": "relative (亲戚)",
  "萌": "to sprout; to bud",
  "炫": "to dazzle; to show off",
  "酌": "to consider; to weigh up",
  "姿": "posture; pose",
  "袁": "surname Yuan",
  "曹": "surname Cao",
  "郭": "surname Guo",
  "斩": "to chop; to cut",
  "逸": "at ease; leisurely",
  "庸": "ordinary; mediocre",
  "掰": "to break off with hands",
  "堡": "fort; castle",
  "搓": "to rub between the hands",
  "鼎": "ancient bronze cauldron",
  "赋": "to give; to endow",
  "酣": "heartily; sound (sleep)",
  "韩": "Korea; surname Han",
  "堪": "can bear; worthy of",
  "腊": "12th lunar month; cured meat",
  "棱": "edge; ridge",
  "缅": "to recall; Myanmar (缅甸)",
  "腔": "cavity; tone of voice",
  "骚": "to disturb; commotion",
  "痴": "silly; crazy about",
  "碌": "busy (忙碌)",
  "谬": "absurd; false",
  "辟": "to open up",
  "蜀": "Shu (old name for Sichuan)",
  "嗦": "as in 哆嗦 (to shiver)",
  "塘": "pond",
  "颖": "clever; novel",
  "辖": "to govern; to administer",
  "澳": "Macao; Australia",
  "磕": "to knock; to bump",
  "擅": "to be good at",
  "爵": "noble title",
  "瞬": "instant; blink",
  "魏": "Wei (state); surname Wei",
  "鹰": "eagle; hawk",
  "嚼": "to chew",
  "髓": "marrow",
  "帖": "invitation; card (请帖)",
  "贾": "surname Jia",
  "倔": "stubborn",
  "粘": "to glue; to stick",
  "荫": "shade (树荫)",
  "咧": "to grin (咧嘴)",
  "唉": "oh; sigh",
  "唠": "to chatter (唠叨)",
  "喇": "horn; trumpet (喇叭)",
  "遛": "to walk (a dog)",
  "曝": "to expose (曝光)",
  "教": "to teach",
  "上": "up; on; to go up",
  "方": "square; direction; side",
  "太": "too; very",
  "午": "noon",
  "元": "dollar (money); first",
  "本": "book; measure word for books",
  "汉": "Chinese (as in 汉语, 汉字)",
  "后": "back; behind; after",
  "考": "to test; to take an exam",
  "老": "old",
  "个": "measure word (one of something)",
  "字": "word; character",
  "告": "to tell; to report",
  "诉": "to tell (as in 告诉)",
  "里": "inside",
  "店": "shop; store",
  "热": "hot",
  "穿": "to wear; to put on",
  "点": "dot; o'clock; a little",
  "奶": "milk; grandma (奶奶)",
  "次": "time (how many times)",
  "谁": "who",
  "话": "words; speech",
  "语": "language; words",
  "楼": "building; floor (storey)",
  "绍": "as in 介绍 (to introduce)",
  "影": "shadow; film (电影)",
  "号": "number; date (几号)",
  "关": "to close; to shut; to turn off",
  "北": "north",
  "准": "accurate; to allow",
  "才": "only then; just; talent",
  "于": "at; in; to",
  "云": "cloud",
  "处": "place; spot",
  "节": "festival; section",
  "卡": "card",
  "讨": "to discuss; to ask for",
  "当": "to be; to act as; when",
  "划": "to plan; to mark off",
  "克": "gram; to overcome",
  "表": "watch; to show",
  "单": "single; list",
  "忽": "suddenly",
  "经": "to pass through; already (已经)",
  "卖": "to sell",
  "其": "other; that; it",
  "所": "place; so (in 所以)",
  "周": "week; around",
  "便": "convenient; handy",
  "春": "spring (season)",
  "度": "degree; measure",
  "封": "to seal; measure word for letters",
  "故": "old; reason; on purpose",
  "结": "knot; to tie",
  "挺": "quite; very",
  "药": "medicine",
  "钟": "clock; bell",
  "铁": "iron",
  "黄": "yellow",
  "理": "reason; to tidy up",
  "猫": "cat",
  "推": "to push",
  "确": "true; correct; really",
  "然": "so; like this",
  "装": "to put in; to install; clothing",
  "墙": "wall",
  "愿": "to wish; to be willing",
  "台": "stage; platform",
  "员": "member; person who works",
  "证": "proof; certificate",
  "录": "to record; to write down",
  "苹": "apple (苹果)",
  "幸": "lucky; fortunate",
  "注": "to pour; to pay attention",
  "整": "whole; tidy; neat",
  "沙": "sand",
  "丰": "plentiful; rich",
  "父": "father",
  "血": "blood",
  "切": "to cut",
  "木": "wood; tree",
  "订": "to book; to order",
  "专": "special; focused on one thing",
  "布": "cloth; to announce",
  "巧": "clever; skillful; by chance",
  "团": "group; ball",
  "困": "sleepy; trapped; difficult",
  "批": "to criticize; to approve; a batch",
  "形": "shape; form",
  "修": "to repair; to fix",
  "效": "effect; result",
  "望": "to look; to hope",
  "领": "to lead; collar",
  "程": "process; journey",
  "景": "scenery; view",
  "属": "to belong to",
  "概": "general; roughly",
  "解": "to untie; to solve",
  "世": "world; lifetime",
  "士": "person; soldier; scholar",
  "巴": "bus (巴士); used in 尾巴 tail",
  "乎": "used in 几乎 (almost), 似乎 (seems)",
  "虫": "insect; bug; worm",
  "伙": "partner; companion; group",
  "企": "business; company (企业)",
  "则": "rule; then",
  "阵": "a short while; a burst (一阵)",
  "局": "office; bureau; game (一局)",
  "秀": "excellent; beautiful",
  "呀": "ah; oh (end-of-sentence sound)",
  "构": "to build; to form; structure",
  "郎": "young man (新郎 = groom)",
  "迫": "to force; urgent",
  "征": "sign; feature; to recruit",
  "甚": "very; even (甚至)",
  "映": "to reflect; to show (a film)",
  "航": "to sail; to fly (航班)",
  "透": "to pass through; see-through",
  "载": "to record; year",
  "寄": "to send by post",
  "婆": "grandma; old woman",
  "森": "forest; full of trees",
  "兴": "happy; interest (高兴, 兴趣)",
  "漂": "pretty (漂亮)",
  "鸭": "duck",
  "卵": "egg",
  "乳": "milk",
  "刘": "Liu (a surname)",
};

/** A 组词's English. */
export const SWEEP_GLOSSES: Record<string, string> = {
  // HSK 5–9 (second sweep)
  "匹配": "to match; to pair up",
  "厉害": "amazing; fierce; severe",
  "摩托": "motorbike",
  "走私": "to smuggle",
  "沟通": "to communicate",
  "驾照": "driver's license",
  "舍不得": "reluctant to part with",
  "大胆": "bold; brave",
  "珍珠": "pearl",
  "桃花": "peach blossom",
  "火锅": "hotpot",
  "麻醉": "anesthesia",
  "心灵": "heart; soul; mind",
  "罢了": "that's all; only",
  "得罪": "to offend (someone)",
  "强盗": "robber; bandit",
  "名副其实": "living up to its name",
  "栋梁": "pillar (of society); beam",
  "爽快": "frank; straightforward",
  "绝缘": "insulation; to insulate",
  "化纤": "synthetic fiber",
  "定心丸": "reassurance; something that sets the mind at ease",
  "呵护": "to cherish; to take good care of",
  "淘汰": "to eliminate; to weed out",
  "弥补": "to make up for",
  "鸦雀无声": "completely silent",
  "规矩": "rules; well-behaved",
  "沾光": "to benefit from others",
  "峡谷": "canyon; gorge",
  "泄露": "to leak (a secret); to reveal",
  "可歌可泣": "deeply moving; heroic",
  "千钧一发": "a critical moment; hanging by a thread",
  "把柄": "something held against sb",
  "烘托": "to set off; to highlight",
  "猖狂": "rampant; unrestrained",
  "收敛": "to restrain oneself; to hold back",
  "耍赖": "to go back on one's word; to act up",
  "马桶": "toilet",
  "淀粉": "starch",
  "奥运会": "Olympic Games",
  "窘迫": "embarrassed; in a fix",
  "大厦": "large building; mansion",
  "粽子": "rice dumpling",
  "追溯": "to trace back",
  "一塌糊涂": "in a complete mess",
  "含蓄": "reserved; implicit",
  "朝三暮四": "fickle; always changing",
  "离谱儿": "outrageous; way off",
  "踊跃": "eager; enthusiastic",
  "跳槽": "to change jobs",
  "澄清": "to clarify",
  "底蕴": "depth; cultural foundation",
  "粗糙": "rough; coarse",
  "雕塑": "sculpture",
  "温馨": "warm and cosy",
  "一块儿": "together",
  "二手": "second-hand",
  "地方": "place",
  "白色": "white",
  "明白": "to understand; clear",
  "东西": "thing; stuff",
  "老汉": "old man",
  "百合": "lily",
  "同学": "classmate",
  "大爷": "uncle; old man (polite)",
  "告诉": "to tell",
  "故事": "story",
  "爬山": "to climb a mountain",
  "出山": "to come out of retirement",
  "三角": "triangle",
  "奶奶": "grandma",
  "不过": "but; however",
  "全身": "the whole body",
  "谁知道": "who knows?",
  "知道": "to know",
  "起来": "to stand up; to get up",
  "高中": "senior high school",
  "不错": "not bad; pretty good",
  "从来": "always; (with 不/没) never",
  "知己": "close friend; best friend",
  "好处": "benefit; advantage",
  "加油": "Go for it! (cheer); to refuel",
  "超市": "supermarket",
  "打印": "to print",
  "红色": "red",
  "恐怕": "I'm afraid; probably",
  "使得": "to make; to cause",
  "直接": "direct; directly",
  "中秋节": "Mid-Autumn Festival",
  "意思": "meaning",
  "咱们": "we (you and me)",
  "酒店": "hotel",
  "早晨": "early morning",
  "黄色": "yellow",
  "懂事": "sensible; well-behaved",
  "电台": "radio station",
  "父亲": "father",
  "把手": "handle; knob",
  "烟花": "fireworks",
  "汤圆": "glutinous rice balls",
  "初中": "junior high school",
  "沙发": "sofa",
  "领导": "leader; to lead",
  "赶到": "to rush to; to arrive in time",
  "退票": "to return a ticket",
  "保安": "security guard",
  "武术": "martial arts",
  "性别": "gender; boy or girl",
  "尾巴": "tail",
  "在乎": "to care about; to mind",
  "叶子": "leaf",
  "耳朵": "ear",
  "阿姨": "auntie; mother's sister",
  "究竟": "after all; actually",
  "抽签": "to draw lots",
  "轮子": "wheel",
  "妻子": "wife",
  "轻松": "relaxed; easy",
  "骨干": "backbone; key member",
  "临时": "temporary; at the last moment",
  "主席": "chairman; chairperson",
  "避暑": "to escape the summer heat",
  "填空": "to fill in the blanks",
  "锻炼": "to exercise; to train",
  "帅哥": "handsome guy",
  "鸭子": "duck",
  "玻璃": "glass",
  "春天": "spring",
};

/** A 组词's pinyin: tones, polyphone readings, 轻声 (裤子 kù zi). */
export const SWEEP_PINYIN: Record<string, string> = {
  // HSK 5–9 (second sweep)
  "池子": "chí zi",
  "帘子": "lián zi",
  "舍不得": "shě bu de",
  "胆子": "dǎn zi",
  "疯子": "fēng zi",
  "一应俱全": "yì yīng jù quán",
  "剪子": "jiǎn zi",
  "肝脏": "gān zàng",
  "炉子": "lú zi",
  "挨打": "ái dǎ",
  "钻空子": "zuān kòng zi",
  "芝麻": "zhī ma",
  "稿子": "gǎo zi",
  "斧子": "fǔ zi",
  "帐子": "zhàng zi",
  "请帖": "qǐng tiě",
  "呜咽": "wū yè",
  "剥夺": "bō duó",
  "商贾": "shāng gǔ",
  "泰斗": "tài dǒu",
  "垫子": "diàn zi",
  "钩子": "gōu zi",
  "蚊子": "wén zi",
  "笛子": "dí zi",
  "铲子": "chǎn zi",
  "梳子": "shū zi",
  "揣测": "chuǎi cè",
  "揣摩": "chuǎi mó",
  "一揽子": "yì lǎn zi",
  "毯子": "tǎn zi",
  "椰子": "yē zi",
  "渣子": "zhā zi",
  "靶子": "bǎ zi",
  "锤子": "chuí zi",
  "凳子": "dèng zi",
  "靴子": "xuē zi",
  "粽子": "zòng zi",
  "橘子": "jú zi",
  "罐头": "guàn tou",
  "豁达": "huò dá",
  "告诉": "gào su",
  "两口子": "liǎng kǒu zi",
  "谢谢": "xiè xie",
  "例子": "lì zi",
  "饺子": "jiǎo zi",
  "月亮": "yuè liang",
  "意思": "yì si",
  "倒是": "dào shì",
  "心脏": "xīn zàng",
  "心脏病": "xīn zàng bìng",
  "船长": "chuán zhǎng",
  "清楚": "qīng chu",
  "事情": "shì qing",
  "眼睛": "yǎn jing",
  "舒服": "shū fu",
  "商量": "shāng liang",
  "把手": "bǎ shou",
  "麻将": "má jiàng",
  "麻烦": "má fan",
  "有朝一日": "yǒu zhāo yí rì",
  "裤子": "kù zi",
  "裙子": "qún zi",
  "箱子": "xiāng zi",
  "甜头": "tián tou",
  "工夫": "gōng fu",
  "功夫": "gōng fu",
  "虫子": "chóng zi",
  "豆子": "dòu zi",
  "肚子": "dù zi",
  "局长": "jú zhǎng",
  "招呼": "zhāo hu",
  "卷入": "juǎn rù",
  "轮子": "lún zi",
  "热闹": "rè nao",
  "粗心大意": "cū xīn dà yì",
  "脑袋": "nǎo dai",
  "率先": "shuài xiān",
  "窗子": "chuāng zi",
  "妻子": "qī zi",
};
