// Content sweep (parent, 2026-10-05): every HSK 1–4 card reviewed for what a P2 child sees — the card's meaning, its 组词's
// pinyin and English — plus a scan of every gloss for slang or adult senses. The dictionary often leads with an archaic sense
// (后 "empress", 店 "inn") or adds slang (鸭子 "male prostitute"); these put the everyday one first.

/** A character's English on its card. */
export const SWEEP_MEANINGS: Record<string, string> = {
  "教": "to teach",
  "上": "up; on; to go up",
  "方": "square; direction; side",
  "太": "too; very",
  "午": "noon",
  "元": "dollar (money); first",
  "本": "book; measure word for books",
  "汉": "Chinese (as in 汉语, 汉字)",
  "后": "back; behind; after",
  "考": "to test; to take an exam",
  "老": "old",
  "个": "measure word (one of something)",
  "字": "word; character",
  "告": "to tell; to report",
  "诉": "to tell (as in 告诉)",
  "里": "inside",
  "店": "shop; store",
  "热": "hot",
  "穿": "to wear; to put on",
  "点": "dot; o'clock; a little",
  "奶": "milk; grandma (奶奶)",
  "次": "time (how many times)",
  "谁": "who",
  "话": "words; speech",
  "语": "language; words",
  "楼": "building; floor (storey)",
  "绍": "as in 介绍 (to introduce)",
  "影": "shadow; film (电影)",
  "号": "number; date (几号)",
  "关": "to close; to shut; to turn off",
  "北": "north",
  "准": "accurate; to allow",
  "才": "only then; just; talent",
  "于": "at; in; to",
  "云": "cloud",
  "处": "place; spot",
  "节": "festival; section",
  "卡": "card",
  "讨": "to discuss; to ask for",
  "当": "to be; to act as; when",
  "划": "to plan; to mark off",
  "克": "gram; to overcome",
  "表": "watch; to show",
  "单": "single; list",
  "忽": "suddenly",
  "经": "to pass through; already (已经)",
  "卖": "to sell",
  "其": "other; that; it",
  "所": "place; so (in 所以)",
  "周": "week; around",
  "便": "convenient; handy",
  "春": "spring (season)",
  "度": "degree; measure",
  "封": "to seal; measure word for letters",
  "故": "old; reason; on purpose",
  "结": "knot; to tie",
  "挺": "quite; very",
  "药": "medicine",
  "钟": "clock; bell",
  "铁": "iron",
  "黄": "yellow",
  "理": "reason; to tidy up",
  "猫": "cat",
  "推": "to push",
  "确": "true; correct; really",
  "然": "so; like this",
  "装": "to put in; to install; clothing",
  "墙": "wall",
  "愿": "to wish; to be willing",
  "台": "stage; platform",
  "员": "member; person who works",
  "证": "proof; certificate",
  "录": "to record; to write down",
  "苹": "apple (苹果)",
  "幸": "lucky; fortunate",
  "注": "to pour; to pay attention",
  "整": "whole; tidy; neat",
  "沙": "sand",
  "丰": "plentiful; rich",
  "父": "father",
  "血": "blood",
  "切": "to cut",
  "木": "wood; tree",
  "订": "to book; to order",
  "专": "special; focused on one thing",
  "布": "cloth; to announce",
  "巧": "clever; skillful; by chance",
  "团": "group; ball",
  "困": "sleepy; trapped; difficult",
  "批": "to criticize; to approve; a batch",
  "形": "shape; form",
  "修": "to repair; to fix",
  "效": "effect; result",
  "望": "to look; to hope",
  "领": "to lead; collar",
  "程": "process; journey",
  "景": "scenery; view",
  "属": "to belong to",
  "概": "general; roughly",
  "解": "to untie; to solve",
  "世": "world; lifetime",
  "士": "person; soldier; scholar",
  "巴": "bus (巴士); used in 尾巴 tail",
  "乎": "used in 几乎 (almost), 似乎 (seems)",
  "虫": "insect; bug; worm",
  "伙": "partner; companion; group",
  "企": "business; company (企业)",
  "则": "rule; then",
  "阵": "a short while; a burst (一阵)",
  "局": "office; bureau; game (一局)",
  "秀": "excellent; beautiful",
  "呀": "ah; oh (end-of-sentence sound)",
  "构": "to build; to form; structure",
  "郎": "young man (新郎 = groom)",
  "迫": "to force; urgent",
  "征": "sign; feature; to recruit",
  "甚": "very; even (甚至)",
  "映": "to reflect; to show (a film)",
  "航": "to sail; to fly (航班)",
  "透": "to pass through; see-through",
  "载": "to record; year",
  "寄": "to send by post",
  "婆": "grandma; old woman",
  "森": "forest; full of trees",
  "兴": "happy; interest (高兴, 兴趣)",
  "漂": "pretty (漂亮)",
  "鸭": "duck",
  "卵": "egg",
  "乳": "milk",
  "刘": "Liu (a surname)",
};

/** A 组词's English. */
export const SWEEP_GLOSSES: Record<string, string> = {
  "一块儿": "together",
  "二手": "second-hand",
  "地方": "place",
  "白色": "white",
  "明白": "to understand; clear",
  "东西": "thing; stuff",
  "老汉": "old man",
  "百合": "lily",
  "同学": "classmate",
  "大爷": "uncle; old man (polite)",
  "告诉": "to tell",
  "故事": "story",
  "爬山": "to climb a mountain",
  "出山": "to come out of retirement",
  "三角": "triangle",
  "奶奶": "grandma",
  "不过": "but; however",
  "全身": "the whole body",
  "谁知道": "who knows?",
  "知道": "to know",
  "起来": "to stand up; to get up",
  "高中": "senior high school",
  "不错": "not bad; pretty good",
  "从来": "always; (with 不/没) never",
  "知己": "close friend; best friend",
  "好处": "benefit; advantage",
  "加油": "Go for it! (cheer); to refuel",
  "超市": "supermarket",
  "打印": "to print",
  "红色": "red",
  "恐怕": "I'm afraid; probably",
  "使得": "to make; to cause",
  "直接": "direct; directly",
  "中秋节": "Mid-Autumn Festival",
  "意思": "meaning",
  "咱们": "we (you and me)",
  "酒店": "hotel",
  "早晨": "early morning",
  "黄色": "yellow",
  "懂事": "sensible; well-behaved",
  "电台": "radio station",
  "父亲": "father",
  "把手": "handle; knob",
  "烟花": "fireworks",
  "汤圆": "glutinous rice balls",
  "初中": "junior high school",
  "沙发": "sofa",
  "领导": "leader; to lead",
  "赶到": "to rush to; to arrive in time",
  "退票": "to return a ticket",
  "保安": "security guard",
  "武术": "martial arts",
  "性别": "gender; boy or girl",
  "尾巴": "tail",
  "在乎": "to care about; to mind",
  "叶子": "leaf",
  "耳朵": "ear",
  "阿姨": "auntie; mother's sister",
  "究竟": "after all; actually",
  "抽签": "to draw lots",
  "轮子": "wheel",
  "妻子": "wife",
  "轻松": "relaxed; easy",
  "骨干": "backbone; key member",
  "临时": "temporary; at the last moment",
  "主席": "chairman; chairperson",
  "避暑": "to escape the summer heat",
  "填空": "to fill in the blanks",
  "锻炼": "to exercise; to train",
  "帅哥": "handsome guy",
  "鸭子": "duck",
  "玻璃": "glass",
  "春天": "spring",
};

/** A 组词's pinyin: tones, polyphone readings, 轻声 (裤子 kù zi). */
export const SWEEP_PINYIN: Record<string, string> = {
  "告诉": "gào su",
  "两口子": "liǎng kǒu zi",
  "谢谢": "xiè xie",
  "例子": "lì zi",
  "饺子": "jiǎo zi",
  "月亮": "yuè liang",
  "意思": "yì si",
  "倒是": "dào shì",
  "心脏": "xīn zàng",
  "心脏病": "xīn zàng bìng",
  "船长": "chuán zhǎng",
  "清楚": "qīng chu",
  "事情": "shì qing",
  "眼睛": "yǎn jing",
  "舒服": "shū fu",
  "商量": "shāng liang",
  "把手": "bǎ shou",
  "麻将": "má jiàng",
  "麻烦": "má fan",
  "有朝一日": "yǒu zhāo yí rì",
  "裤子": "kù zi",
  "裙子": "qún zi",
  "箱子": "xiāng zi",
  "甜头": "tián tou",
  "工夫": "gōng fu",
  "功夫": "gōng fu",
  "虫子": "chóng zi",
  "豆子": "dòu zi",
  "肚子": "dù zi",
  "局长": "jú zhǎng",
  "招呼": "zhāo hu",
  "卷入": "juǎn rù",
  "轮子": "lún zi",
  "热闹": "rè nao",
  "粗心大意": "cū xīn dà yì",
  "脑袋": "nǎo dai",
  "率先": "shuài xiān",
  "窗子": "chuāng zi",
  "妻子": "qī zi",
};
