// English for the bank's clues, shown under the Chinese clue on the sheet after a miss (spec 2026-10-05 §3.6; sweep). Written
// for this app; the clue itself stays Chinese.
export const CLUE_EN: Record<string, string> = {
  保持: '保持 keeps something as it is; 保护 keeps it from harm',
  比较: '比较 = rather, a bit; 比赛 = a match',
  决定: '决定 = decide what to do; 解决 = solve a problem',
  解决: '决定 = decide what to do; 解决 = solve a problem',
  保护: '保护 keeps something from harm; 保持 keeps it as it is',
  连忙: '连忙 tells what someone did at once; to hurry someone, say 赶快',
  赶快: 'to tell someone to hurry, say 赶快 (not 连忙)',
  赶紧: 'to tell someone to hurry, say 赶紧 (not 连忙)',
  从来: '从来 is usually followed by 不 or 没 (never)',
  不仅: 'not only … but also … (不仅……还……)',
  只有: 'only if … (只有……才……); as long as … (只要……就……)',
  理解: '理解 = understand; 理发 = have a haircut',
  希望: '希望 = hope something good happens; 失望 = disappointed',
  比赛: '比赛 = a match; 比较 = rather, a bit',
  整齐: '整齐 = neat and tidy; 整理 = to tidy up',
  失望: '希望 = hope; 失望 = disappointed when it did not happen',
  兴趣: '有兴趣 = interested (a noun); 很有趣 = fun (describes something)',
  无论: 'no matter … (无论……都……)',
  让: '让 = ask or let someone do something',
  已经: '已经 = already done',
  帮助: '帮助 can take a person after it; 帮忙 cannot',
  但是: 'use 但是 (but) when the two parts go different ways',
  而且: 'not only … but also … (不但……而且……)',
  虽然: 'with 但是 later, start with 虽然 (although)',
  所以: 'after 因为 (because), use 所以 (so)',
  因为: 'before 所以 (so), use 因为 (because)',
  如果: 'with 就 later, start with 如果 (if)',
  或者: 'in a question use 还是; otherwise use 或者 (or)',
  刚才: '刚才 = just now, a moment ago',
  不但: 'not only … but also … (不但……而且……)',
  只要: 'with 就 later, start with 只要 (as long as)',
  跟: '跟 = together with someone',
  看: 'music is something you listen to (听), not look at',
  买: '买 = give money, take the thing',
  知道: 'you 认识 a person; you 知道 a fact',
  认识: 'you 认识 a person; you 知道 a fact',
};
