import type { BankItem } from '../sentenceBank';

/** HSK 1 words in use. Written for this app: everyday sentences a P2 child can read (HSK 1–2 characters only). */
export const BANK_1: BankItem[] = [
  { word: '很', type: 'adv', gaps: [{ text: '今天＿热。', wrong: ['在', '和', '跟'] }, { text: '这个书包＿大。', wrong: ['和', '在', '给'] }], misuse: '我很一个书包。' },
  { word: '在', type: 'prep', gaps: [{ text: '妈妈＿家里做饭。', wrong: ['很', '和', '对'] }, { text: '书包＿桌子上。', wrong: ['很', '给', '和'] }], misuse: '我在很高兴。' },
  { word: '和', type: 'conj', gaps: [{ text: '我＿哥哥都喜欢打球。', wrong: ['很', '在', '对'] }, { text: '爸爸＿妈妈去买东西。', wrong: ['很', '对', '会'] }], misuse: '今天和热。' },
  { word: '跟', type: 'prep', gaps: [{ text: '我＿妈妈去公园。', wrong: ['很', '银', '对'] }, { text: '你＿我来。', wrong: ['很', '是', '银'] }], misuse: '我跟很高兴。', clue: '跟：和别人一起' },
  { word: '给', type: 'prep', gaps: [{ text: '妈妈＿我买了一本书。', wrong: ['很', '是', '去'] }, { text: '我＿你写信。', wrong: ['很', '是', '吃'] }], misuse: '这个书包很给。' },
  { word: '对', type: 'adj', gaps: [{ text: '你说得＿。', wrong: ['在', '和', '去'] }, { text: '老师＿我们很好。', wrong: ['在', '是', '去'] }], misuse: '我对去学校。' },
  { word: '想', type: 'v', gaps: [{ text: '我＿喝水。', wrong: ['很', '和', '对'] }, { text: '我很＿妈妈。', wrong: ['去', '吃', '在'] }], misuse: '这本书很想。' },
  { word: '要', type: 'v', gaps: [{ text: '我＿去上学了。', wrong: ['很', '和', '对'] }, { text: '你＿多喝水。', wrong: ['很', '和', '在'] }], misuse: '我要很。' },
  { word: '会', type: 'v', gaps: [{ text: '我＿写我的名字。', wrong: ['很', '和', '对'] }, { text: '明天＿下雨。', wrong: ['很', '和', '对'] }], misuse: '我会很书。' },
  { word: '能', type: 'v', gaps: [{ text: '你＿来我家玩吗？', wrong: ['很', '和', '对'] }, { text: '他病了，不＿上学。', wrong: ['很', '和', '也'] }], misuse: '我能一本书。' },
  { word: '吃', type: 'v', gaps: [{ text: '我们一起＿饭吧。', wrong: ['喝', '看', '写'] }, { text: '小猫在＿鱼。', wrong: ['喝', '读', '写'] }], misuse: '我吃了一杯水。' },
  { word: '喝', type: 'v', gaps: [{ text: '我想＿一杯水。', wrong: ['吃', '看', '写'] }, { text: '爷爷天天＿茶。', wrong: ['跑', '写', '读'] }], misuse: '我喝了一个面包。' },
  { word: '看', type: 'v', gaps: [{ text: '我们去＿电影吧。', wrong: ['喝', '吃', '说'] }, { text: '我在＿书。', wrong: ['喝', '吃', '走'] }], misuse: '哥哥在看音乐。', clue: '音乐要用耳朵听' },
  { word: '听', type: 'v', gaps: [{ text: '我喜欢＿歌。', wrong: ['吃', '喝', '跑'] }, { text: '上课要＿老师说话。', wrong: ['吃', '喝', '坐'] }], misuse: '我听了一个面包。' },
  { word: '说', type: 'v', gaps: [{ text: '他＿他很高兴。', wrong: ['吃', '喝', '跑'] }, { text: '请你＿慢一点。', wrong: ['书', '门', '饭'] }], misuse: '我说了一碗饭。' },
  { word: '读', type: 'v', gaps: [{ text: '我天天＿书。', wrong: ['喝', '吃', '跑'] }, { text: '请你大声＿这个字。', wrong: ['喝', '吃', '跑'] }], misuse: '我读了一杯茶。' },
  { word: '写', type: 'v', gaps: [{ text: '我会＿我自己的名字。', wrong: ['喝', '吃', '跑'] }, { text: '老师在黑板上＿字。', wrong: ['喝', '吃', '跑'] }], misuse: '我写了一杯水。' },
  { word: '买', type: 'v', gaps: [{ text: '妈妈去商店＿菜。', wrong: ['写', '读', '喝'] }, { text: '我想＿一本新书。', wrong: ['喝', '吃', '跑'] }], misuse: '我买了一个朋友。', clue: '买：给钱，拿东西' },
  { word: '走', type: 'v', gaps: [{ text: '我们＿路去学校。', wrong: ['吃', '喝', '写'] }, { text: '你往前＿就到了。', wrong: ['吃', '喝', '写'] }], misuse: '我走了一碗饭。' },
  { word: '跑', type: 'v', gaps: [{ text: '下课了，同学们＿到外面玩。', wrong: ['吃', '喝', '写'] }, { text: '小狗＿过来了。', wrong: ['吃', '喝', '写'] }], misuse: '我跑了一本书。' },
  { word: '坐', type: 'v', gaps: [{ text: '请＿下。', wrong: ['吃', '喝', '书'] }, { text: '我们＿车去学校。', wrong: ['吃', '喝', '写'] }], misuse: '我坐了一杯水。' },
  { word: '开', type: 'v', gaps: [{ text: '请＿门。', wrong: ['吃', '喝', '坐'] }, { text: '爸爸会＿车。', wrong: ['吃', '喝', '写'] }], misuse: '我开了一碗饭。' },
  { word: '关', type: 'v', gaps: [{ text: '下雨了，快＿门。', wrong: ['吃', '喝', '写'] }, { text: '睡觉前要＿灯。', wrong: ['吃', '喝', '写'] }], misuse: '妹妹关了一杯水。' },
  { word: '送', type: 'v', gaps: [{ text: '爸爸＿我去学校。', wrong: ['吃', '喝', '写'] }, { text: '我＿妈妈一本书。', wrong: ['吃', '喝', '写'] }], misuse: '我送了很高兴。' },
  { word: '等', type: 'v', gaps: [{ text: '请＿一下。', wrong: ['很', '和', '的'] }, { text: '我在门口＿你。', wrong: ['喝', '吃', '写'] }], misuse: '我等很大。' },
  { word: '找', type: 'v', gaps: [{ text: '我在＿我的书包。', wrong: ['喝', '吃', '跑'] }, { text: '你明天来学校＿我吧。', wrong: ['喝', '吃', '写'] }], misuse: '这个书包很找。' },
  { word: '穿', type: 'v', gaps: [{ text: '天冷了，要多＿衣服。', wrong: ['吃', '喝', '写'] }, { text: '妹妹＿了一件红衣服。', wrong: ['吃', '喝', '写'] }], misuse: '我穿了一碗饭。' },
  { word: '洗', type: 'v', gaps: [{ text: '吃饭前要＿手。', wrong: ['吃', '喝', '写'] }, { text: '妈妈在＿碗。', wrong: ['吃', '喝', '写'] }], misuse: '我洗了一个问题。' },
  { word: '玩', type: 'v', gaps: [{ text: '下课了，我们去外面＿。', wrong: ['书', '字', '门'] }, { text: '弟弟喜欢跟小狗＿。', wrong: ['吃', '写', '读'] }], misuse: '我玩很高。' },
  { word: '学', type: 'v', gaps: [{ text: '我在＿写字。', wrong: ['吃', '喝', '跑'] }, { text: '妹妹在＿唱歌。', wrong: ['吃', '喝', '跑'] }], misuse: '我学了一碗饭。' },
  { word: '教', type: 'v', gaps: [{ text: '老师＿我们写字。', wrong: ['吃', '喝', '跑'] }, { text: '妈妈＿我做饭。', wrong: ['吃', '喝', '跑'] }], misuse: '我教了一杯水。' },
  { word: '做', type: 'v', gaps: [{ text: '我在＿作业。', wrong: ['吃', '喝', '跑'] }, { text: '奶奶会＿包子。', wrong: ['喝', '读', '跑'] }], misuse: '我做了很高。' },
  { word: '用', type: 'v', gaps: [{ text: '我＿笔写字。', wrong: ['吃', '喝', '跑'] }, { text: '你会＿电脑吗？', wrong: ['吃', '喝', '跑'] }], misuse: '我用很开心。' },
  { word: '放', type: 'v', gaps: [{ text: '书包＿在桌子上。', wrong: ['吃', '喝', '跑'] }, { text: '我们明天＿假。', wrong: ['吃', '喝', '写'] }], misuse: '我放很高兴。' },
  { word: '拿', type: 'v', gaps: [{ text: '我去＿一本书。', wrong: ['喝', '吃', '跑'] }, { text: '你手里＿着什么？', wrong: ['喝', '吃', '跑'] }], misuse: '我拿很快乐。' },
  { word: '住', type: 'v', gaps: [{ text: '我＿在这里。', wrong: ['吃', '喝', '写'] }, { text: '爷爷奶奶＿在我家。', wrong: ['吃', '喝', '写'] }], misuse: '我住了一碗饭。' },
  { word: '叫', type: 'v', gaps: [{ text: '他＿什么名字？', wrong: ['吃', '喝', '跑'] }, { text: '妈妈在＿我回家。', wrong: ['吃', '喝', '写'] }], misuse: '这本书很叫。' },
  { word: '问', type: 'v', gaps: [{ text: '你可以＿他。', wrong: ['吃', '喝', '跑'] }, { text: '有不会的就要＿。', wrong: ['吃', '喝', '跑'] }], misuse: '我问了一碗饭。' },
  { word: '回', type: 'v', gaps: [{ text: '我们五点＿家。', wrong: ['吃', '喝', '写'] }, { text: '下课了，同学们＿到教室。', wrong: ['吃', '喝', '写'] }], misuse: '这个书包很回。' },
  { word: '进', type: 'v', gaps: [{ text: '请＿来。', wrong: ['吃', '喝', '写'] }, { text: '他跑＿了教室。', wrong: ['吃', '喝', '写'] }], misuse: '我进很高兴。' },
  { word: '出', type: 'v', gaps: [{ text: '我们＿去玩吧。', wrong: ['吃', '喝', '写'] }, { text: '太阳＿来了。', wrong: ['吃', '喝', '写'] }], misuse: '我出了一碗饭。' },
  { word: '到', type: 'v', gaps: [{ text: '我们＿学校了。', wrong: ['吃', '喝', '写'] }, { text: '车站＿了，下车吧。', wrong: ['吃', '喝', '写'] }], misuse: '我到很高兴。' },
  { word: '大', type: 'adj', gaps: [{ text: '这只狗很＿。', wrong: ['跑', '吃', '去'] }, { text: '雨下得很＿。', wrong: ['跑', '吃', '去'] }], misuse: '我大去学校。' },
  { word: '小', type: 'adj', gaps: [{ text: '这个书包太＿了。', wrong: ['跑', '吃', '去'] }, { text: '我的弟弟还＿。', wrong: ['吃', '去', '喝'] }], misuse: '我小了一杯水。' },
  { word: '多', type: 'adj', gaps: [{ text: '公园里有很＿人。', wrong: ['跑', '吃', '去'] }, { text: '今天的作业很＿。', wrong: ['跑', '吃', '去'] }], misuse: '多我喝水。' },
  { word: '少', type: 'adj', gaps: [{ text: '今天来的人很＿。', wrong: ['跑', '吃', '去'] }, { text: '水太＿了。', wrong: ['跑', '吃', '去'] }], misuse: '少我吃饭。' },
  { word: '高', type: 'adj', gaps: [{ text: '哥哥比我＿。', wrong: ['吃', '去', '跑'] }, { text: '这座山很＿。', wrong: ['吃', '去', '跑'] }], misuse: '我高了一碗饭。' },
  { word: '新', type: 'adj', gaps: [{ text: '我有一个＿书包。', wrong: ['吃', '去', '跑'] }, { text: '这是我的＿朋友。', wrong: ['吃', '去', '跑'] }], misuse: '我新去学校。' },
  { word: '快', type: 'adj', gaps: [{ text: '他跑得很＿。', wrong: ['吃', '去', '坐'] }, { text: '＿点来吧！', wrong: ['吃', '去', '坐'] }], misuse: '这本书很快吃。' },
  { word: '慢', type: 'adj', gaps: [{ text: '请你走＿一点。', wrong: ['吃', '去', '坐'] }, { text: '奶奶走得很＿。', wrong: ['吃', '去', '坐'] }], misuse: '我慢一本书。' },
  { word: '冷', type: 'adj', gaps: [{ text: '冬天很＿。', wrong: ['吃', '去', '坐'] }, { text: '今天好＿，要多穿一件衣服。', wrong: ['吃', '去', '坐'] }], misuse: '我冷去学校。' },
  { word: '热', type: 'adj', gaps: [{ text: '夏天很＿。', wrong: ['吃', '去', '坐'] }, { text: '这杯水太＿了。', wrong: ['吃', '去', '坐'] }], misuse: '我热一本书。' },
  { word: '远', type: 'adj', gaps: [{ text: '我家离学校很＿。', wrong: ['吃', '去', '坐'] }, { text: '公园不＿，走路就到了。', wrong: ['吃', '去', '坐'] }], misuse: '我远吃饭。' },
  { word: '早', type: 'adj', gaps: [{ text: '我今天起得很＿。', wrong: ['吃', '去', '坐'] }, { text: '你来得真＿。', wrong: ['吃', '去', '坐'] }], misuse: '我早一本书。' },
  { word: '晚', type: 'adj', gaps: [{ text: '我今天来＿了。', wrong: ['吃', '去', '坐'] }, { text: '天＿了，我们走吧。', wrong: ['吃', '去', '坐'] }], misuse: '我晚一杯水。' },
  { word: '忙', type: 'adj', gaps: [{ text: '爸爸今天很＿。', wrong: ['吃', '去', '坐'] }, { text: '妈妈在＿什么？', wrong: ['去', '坐', '很'] }], misuse: '我忙了一碗饭。' },
  { word: '累', type: 'adj', gaps: [{ text: '跑了很久，我很＿。', wrong: ['吃', '去', '坐'] }, { text: '你＿了就休息一下。', wrong: ['吃', '去', '坐'] }], misuse: '我累一本书。' },
  { word: '爸爸', type: 'n', gaps: [{ text: '我＿是医生。', wrong: ['学校', '东西', '天气'] }, { text: '＿天天开车上班。', wrong: ['学校', '东西', '天气'] }], misuse: '我很爸爸。' },
  { word: '朋友', type: 'n', gaps: [{ text: '他是我的好＿。', wrong: ['喜欢', '知道', '起床'] }, { text: '我和＿一起玩。', wrong: ['喜欢', '知道', '起床'] }], misuse: '我朋友了一本书。' },
  { word: '知道', type: 'v', gaps: [{ text: '我不＿他住在哪里。', wrong: ['认识', '喜欢', '起床'] }, { text: '你＿怎么去公园吗？', wrong: ['认识', '喜欢', '告诉'] }], misuse: '我知道了一碗饭。', clue: '认识一个人；知道一件事' },
  { word: '明白', type: 'v', gaps: [{ text: '老师说的我都＿了。', wrong: ['朋友', '东西', '衣服'] }, { text: '你＿我的意思吗？', wrong: ['朋友', '东西', '认识'] }], misuse: '我明白了一杯水。' },
  { word: '喜欢', type: 'v', gaps: [{ text: '我＿吃面条。', wrong: ['朋友', '东西', '衣服'] }, { text: '妹妹很＿小猫。', wrong: ['朋友', '东西', '起床'] }], misuse: '我喜欢很高兴。' },
  { word: '觉得', type: 'v', gaps: [{ text: '我＿今天很冷。', wrong: ['朋友', '东西', '衣服'] }, { text: '你＿这本书好看吗？', wrong: ['朋友', '东西', '起床'] }], misuse: '我觉得了一个书包。' },
  { word: '认识', type: 'v', gaps: [{ text: '我＿他，他是我的同学。', wrong: ['东西', '衣服', '学校'] }, { text: '很高兴＿你！', wrong: ['东西', '衣服', '学校'] }], misuse: '我认识了一碗饭。', clue: '认识一个人；知道一件事' },
  { word: '记住', type: 'v', gaps: [{ text: '请＿老师的话。', wrong: ['东西', '衣服', '学校'] }, { text: '我＿了这个字。', wrong: ['东西', '衣服', '学校'] }], misuse: '我记住了一碗饭。' },
  { word: '告诉', type: 'v', gaps: [{ text: '妈妈＿我明天下雨。', wrong: ['东西', '衣服', '学校'] }, { text: '请你＿我你的名字。', wrong: ['东西', '衣服', '学校'] }], misuse: '我告诉了一杯水。' },
  { word: '准备', type: 'v', gaps: [{ text: '我在＿明天的考试。', wrong: ['东西', '衣服', '朋友'] }, { text: '妈妈＿好了晚饭。', wrong: ['东西', '衣服', '朋友'] }], misuse: '我准备很高。' },
  { word: '帮忙', type: 'v', gaps: [{ text: '你能来＿吗？', wrong: ['东西', '衣服', '学校'] }, { text: '谢谢你来＿！', wrong: ['东西', '衣服', '学校'] }], misuse: '我帮忙了一本书。' },
  { word: '休息', type: 'v', gaps: [{ text: '我累了，想＿一下。', wrong: ['东西', '衣服', '学校'] }, { text: '下课了，大家＿一会儿。', wrong: ['东西', '衣服', '学校'] }], misuse: '我休息了一个书包。' },
  { word: '起床', type: 'v', gaps: [{ text: '我天天七点＿。', wrong: ['东西', '衣服', '学校'] }, { text: '快＿，要上学了！', wrong: ['东西', '衣服', '学校'] }], misuse: '我起床了一碗饭。' },
  { word: '睡觉', type: 'v', gaps: [{ text: '晚上九点我就去＿。', wrong: ['东西', '衣服', '学校'] }, { text: '小猫在床上＿。', wrong: ['东西', '衣服', '学校'] }], misuse: '我睡觉了一本书。' },
  { word: '回答', type: 'v', gaps: [{ text: '请你＿这个问题。', wrong: ['东西', '衣服', '学校'] }, { text: '他＿得很对。', wrong: ['东西', '衣服', '学校'] }], misuse: '我回答了一碗饭。' },
  { word: '认真', type: 'adj', gaps: [{ text: '他上课很＿。', wrong: ['东西', '衣服', '学校'] }, { text: '我们要＿写字。', wrong: ['东西', '衣服', '学校'] }], misuse: '我认真了一本书。' },
  { word: '干净', type: 'adj', gaps: [{ text: '我的房间很＿。', wrong: ['东西', '衣服', '学校'] }, { text: '这件衣服很＿。', wrong: ['东西', '朋友', '学校'] }], misuse: '我干净吃饭。' },
  { word: '高兴', type: 'adj', gaps: [{ text: '今天我很＿。', wrong: ['东西', '衣服', '学校'] }, { text: '见到你我很＿。', wrong: ['东西', '衣服', '学校'] }], misuse: '我高兴了一碗饭。' },
  { word: '一起', type: 'adv', gaps: [{ text: '我们＿去公园吧。', wrong: ['东西', '衣服', '学校'] }, { text: '我和妹妹＿唱歌。', wrong: ['东西', '衣服', '学校'] }], misuse: '一起我很高兴。' },
  { word: '常常', type: 'adv', gaps: [{ text: '我＿去图书馆。', wrong: ['东西', '衣服', '学校'] }, { text: '爷爷＿去公园走路。', wrong: ['东西', '衣服', '学校'] }], misuse: '这本书很常常。' },
  { word: '马上', type: 'adv', gaps: [{ text: '我＿就来！', wrong: ['东西', '衣服', '学校'] }, { text: '要上课了，我们＿回教室。', wrong: ['东西', '衣服', '学校'] }], misuse: '我马上了一本书。' },
  { word: '非常', type: 'adv', gaps: [{ text: '今天＿热。', wrong: ['东西', '衣服', '学校'] }, { text: '这个故事＿好听。', wrong: ['东西', '衣服', '学校'] }], misuse: '我非常一本书。' },
  { word: '还是', type: 'conj', gaps: [{ text: '你喝茶＿喝水？', wrong: ['东西', '衣服', '学校'] }, { text: '我们走路去＿坐车去？', wrong: ['东西', '衣服', '学校'] }], misuse: '我还是了一碗饭。' },
  { word: '一样', type: 'adj', gaps: [{ text: '我和哥哥＿高。', wrong: ['东西', '衣服', '学校'] }, { text: '这两本书不＿。', wrong: ['东西', '衣服', '学校'] }], misuse: '一样我去学校。' },
  { word: '旁边', type: 'n', gaps: [{ text: '我家＿有一个公园。', wrong: ['东西', '衣服', '起床'] }, { text: '他坐在我＿。', wrong: ['东西', '衣服', '起床'] }], misuse: '我旁边了一本书。' },
  { word: '时候', type: 'n', gaps: [{ text: '你什么＿来？', wrong: ['东西', '衣服', '学校'] }, { text: '我小的＿很喜欢画画。', wrong: ['东西', '衣服', '学校'] }], misuse: '我时候去学校。' },
  { word: '一会儿', type: 'n', gaps: [{ text: '请等＿。', wrong: ['图书馆', '对不起', '不客气'] }, { text: '我们休息＿吧。', wrong: ['图书馆', '洗手间', '星期天'] }], misuse: '我一会儿了一碗饭。' },
  { word: '衣服', type: 'n', gaps: [{ text: '我穿了一件新＿。', wrong: ['朋友', '学校', '起床'] }, { text: '妈妈在洗＿。', wrong: ['朋友', '学校', '起床'] }], misuse: '我喝了一件衣服。' },
  { word: '东西', type: 'n', gaps: [{ text: '我去商店买＿。', wrong: ['朋友', '起床', '睡觉'] }, { text: '你的书包里有什么＿？', wrong: ['朋友', '起床', '睡觉'] }], misuse: '我东西了很多。' },
  { word: '名字', type: 'n', gaps: [{ text: '你叫什么＿？', wrong: ['起床', '睡觉', '喜欢'] }, { text: '请写上你的＿。', wrong: ['起床', '睡觉', '喜欢'] }], misuse: '我名字去学校。' },
  { word: '学校', type: 'n', gaps: [{ text: '我天天走路去＿。', wrong: ['起床', '睡觉', '喜欢'] }, { text: '我们的＿很大。', wrong: ['起床', '睡觉', '喜欢'] }], misuse: '我学校了一本书。' },
  { word: '同学', type: 'n', gaps: [{ text: '他是我的＿。', wrong: ['起床', '睡觉', '喜欢'] }, { text: '下课了，＿们去外面玩。', wrong: ['起床', '睡觉', '喜欢'] }], misuse: '我同学了一碗饭。' },
  { word: '图书馆', type: 'n', gaps: [{ text: '我去＿看书。', wrong: ['星期天', '小朋友', '对不起'] }, { text: '＿里要安静。', wrong: ['星期天', '小朋友', '对不起'] }], misuse: '我图书馆了一本书。' },
  { word: '介绍', type: 'v', gaps: [{ text: '我来＿一下我的家人。', wrong: ['起床', '睡觉', '东西'] }, { text: '老师给我们＿了一个新同学。', wrong: ['起床', '睡觉', '东西'] }], misuse: '我介绍很高。' },
  { word: '生气', type: 'adj', gaps: [{ text: '妈妈很＿。', wrong: ['起床', '东西', '衣服'] }, { text: '别＿了，我们一起玩吧。', wrong: ['起床', '东西', '衣服'] }], misuse: '我生气了一本书。' },
  { word: '忘记', type: 'v', gaps: [{ text: '我＿带书包了。', wrong: ['起床', '东西', '衣服'] }, { text: '别＿关门。', wrong: ['起床', '东西', '衣服'] }], misuse: '我忘记很高兴。' },
  { word: '重要', type: 'adj', gaps: [{ text: '这件事很＿。', wrong: ['起床', '东西', '衣服'] }, { text: '上课听老师说话很＿。', wrong: ['起床', '东西', '衣服'] }], misuse: '我重要去学校。' },
  { word: '考试', type: 'n', gaps: [{ text: '明天有＿。', wrong: ['起床', '睡觉', '喜欢'] }, { text: '我这次＿考得很好。', wrong: ['起床', '睡觉', '喜欢'] }], misuse: '我考试了一碗饭。' },
  { word: '上课', type: 'v', gaps: [{ text: '我们八点＿。', wrong: ['东西', '衣服', '朋友'] }, { text: '＿的时候不能说话。', wrong: ['东西', '衣服', '朋友'] }], misuse: '我上课了一本书。' },
  { word: '放学', type: 'v', gaps: [{ text: '＿后我回家。', wrong: ['东西', '衣服', '朋友'] }, { text: '我们四点＿。', wrong: ['东西', '衣服', '朋友'] }], misuse: '我放学了一杯水。' },
  { word: '打开', type: 'v', gaps: [{ text: '请＿门。', wrong: ['东西', '衣服', '朋友'] }, { text: '＿书，看第十页。', wrong: ['东西', '衣服', '朋友'] }], misuse: '我打开了很高兴。', pair: '门' },
  { word: '关上', type: 'v', gaps: [{ text: '请＿门。', wrong: ['东西', '衣服', '朋友'] }, { text: '天黑了，＿灯吧。', wrong: ['东西', '衣服', '朋友'] }], misuse: '我关上了一碗饭。', pair: '门' },
  { word: '回家', type: 'v', gaps: [{ text: '放学后我就＿。', wrong: ['东西', '衣服', '朋友'] }, { text: '天晚了，我们＿吧。', wrong: ['东西', '衣服', '朋友'] }], misuse: '我回家了一碗饭。' },
  { word: '天气', type: 'n', gaps: [{ text: '今天＿很好。', wrong: ['东西', '衣服', '朋友'] }, { text: '明天的＿会很冷。', wrong: ['东西', '衣服', '朋友'] }], misuse: '我天气去学校。' },
  { word: '一边', type: 'n', gaps: [{ text: '路的＿有很多树。', wrong: ['东西', '衣服', '朋友'] }, { text: '桌子的＿有一个书包。', wrong: ['东西', '衣服', '朋友'] }], misuse: '我一边了一本书。' },
  { word: '别人', type: 'pron', gaps: [{ text: '不要拿＿的东西。', wrong: ['起床', '睡觉', '喜欢'] }, { text: '我们要帮助＿。', wrong: ['起床', '睡觉', '喜欢'] }], misuse: '我别人去学校。' },
];
